package org.eclipse.txray.jdbc;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.Time;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.TreeMap;

import org.eclipse.txray.jdbc.backend.ExecuteRequest;
import org.eclipse.txray.jdbc.backend.ExecuteResult;
import org.eclipse.txray.jdbc.backend.Param;

/** Statement, PreparedStatement and CallableStatement (IN parameters only). */
final class StatementHandler extends JdbcHandler {

    private final TxRayConnection connection;
    /** SQL of a prepared statement, null for a plain statement. */
    private final String preparedSql;
    private final TreeMap<Integer, Param> params = new TreeMap<>();
    private ResultSet resultSet;
    private long updateCount = -1;
    private long maxRows;
    private int fetchSize;
    private int queryTimeout;
    private boolean closed;

    StatementHandler(TxRayConnection connection, String preparedSql) {
        this.connection = connection;
        this.preparedSql = preparedSql;
    }

    private boolean run(String sql, boolean prepared) throws SQLException {
        if (closed) {
            throw new SQLException("Statement is closed", "HY010");
        }
        closeCurrent();
        ExecuteRequest request = new ExecuteRequest();
        request.sql = sql;
        request.maxRows = (int) Math.min(Integer.MAX_VALUE, maxRows);
        if (prepared) {
            request.params = new ArrayList<>();
            int expected = params.isEmpty() ? 0 : params.lastKey();
            for (int i = 1; i <= expected; i++) {
                Param p = params.get(i);
                if (p == null) {
                    throw new SQLException("No value specified for parameter " + i, "07001");
                }
                request.params.add(p);
            }
        }
        ExecuteResult result = connection.execute(request);
        if (result.kind == ExecuteResult.ROWS) {
            resultSet = new ResultSetHandler(self(), result.columns, result.rows).proxy(ResultSet.class);
            updateCount = -1;
            if (result.truncated) {
                warning = new SQLWarning("TxRay: result truncated to " + result.rows.size() + " rows");
            }
            return true;
        }
        updateCount = result.updateCount;
        return false;
    }

    private SQLWarning warning;

    private void closeCurrent() throws SQLException {
        if (resultSet != null) {
            resultSet.close();
            resultSet = null;
        }
        updateCount = -1;
        warning = null;
    }

    private void requirePlain() throws SQLException {
        if (preparedSql != null) {
            throw new SQLException("Method not allowed on a PreparedStatement", "HY000");
        }
    }

    // ---- execution -----------------------------------------------------------------------

    public ResultSet executeQuery(String sql) throws SQLException {
        requirePlain();
        if (!run(sql, false)) {
            throw new SQLException("Statement did not return a result set", "02000");
        }
        return resultSet;
    }

    public ResultSet executeQuery() throws SQLException {
        if (!run(preparedSql, true)) {
            throw new SQLException("Statement did not return a result set", "02000");
        }
        return resultSet;
    }

    public boolean execute(String sql) throws SQLException {
        requirePlain();
        return run(sql, false);
    }

    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return execute(sql);
    }

    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return execute(sql);
    }

    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return execute(sql);
    }

    public boolean execute() throws SQLException {
        return run(preparedSql, true);
    }

    public int executeUpdate(String sql) throws SQLException {
        return (int) executeLargeUpdate(sql);
    }

    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return executeUpdate(sql);
    }

    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return executeUpdate(sql);
    }

    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return executeUpdate(sql);
    }

    public int executeUpdate() throws SQLException {
        return (int) executeLargeUpdate();
    }

    public long executeLargeUpdate(String sql) throws SQLException {
        requirePlain();
        run(sql, false);
        return Math.max(updateCount, 0);
    }

    public long executeLargeUpdate() throws SQLException {
        run(preparedSql, true);
        return Math.max(updateCount, 0);
    }

    public void addBatch(String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException("Batches are not supported by TxRay");
    }

    public void addBatch() throws SQLException {
        throw new SQLFeatureNotSupportedException("Batches are not supported by TxRay");
    }

    public int[] executeBatch() throws SQLException {
        throw new SQLFeatureNotSupportedException("Batches are not supported by TxRay");
    }

    public ResultSet getResultSet() {
        return resultSet;
    }

    public int getUpdateCount() {
        return (int) updateCount;
    }

    public long getLargeUpdateCount() {
        return updateCount;
    }

    public boolean getMoreResults() throws SQLException {
        closeCurrent();
        return false;
    }

    public boolean getMoreResults(int current) throws SQLException {
        return getMoreResults();
    }

    public ResultSet getGeneratedKeys() {
        return ResultSetHandler.empty();
    }

    // ---- settings ------------------------------------------------------------------------

    public int getMaxRows() {
        return (int) maxRows;
    }

    public void setMaxRows(int max) {
        maxRows = max;
    }

    public long getLargeMaxRows() {
        return maxRows;
    }

    public void setLargeMaxRows(long max) {
        maxRows = max;
    }

    public int getFetchSize() {
        return fetchSize;
    }

    public void setFetchSize(int rows) {
        fetchSize = rows;
    }

    public int getQueryTimeout() {
        return queryTimeout;
    }

    public void setQueryTimeout(int seconds) {
        queryTimeout = seconds;
    }

    public int getResultSetType() {
        return ResultSet.TYPE_SCROLL_INSENSITIVE;
    }

    public int getResultSetConcurrency() {
        return ResultSet.CONCUR_READ_ONLY;
    }

    public int getResultSetHoldability() {
        return ResultSet.HOLD_CURSORS_OVER_COMMIT;
    }

    public int getFetchDirection() {
        return ResultSet.FETCH_FORWARD;
    }

    public Connection getConnection() {
        return (Connection) connection.self();
    }

    public SQLWarning getWarnings() {
        return warning;
    }

    public void clearWarnings() {
        warning = null;
    }

    public void cancel() {
        // a JDI invocation cannot be interrupted
    }

    public void close() throws SQLException {
        closeCurrent();
        closed = true;
    }

    public boolean isClosed() {
        return closed;
    }

    // ---- parameters ----------------------------------------------------------------------

    private void set(int index, byte kind, int sqlType, String value) throws SQLException {
        if (index < 1) {
            throw new SQLException("Invalid parameter index " + index, "07009");
        }
        params.put(index, value == null ? new Param(Param.NULL, sqlType, null) : new Param(kind, sqlType, value));
    }

    public void clearParameters() {
        params.clear();
    }

    public void setNull(int i, int sqlType) throws SQLException {
        set(i, Param.NULL, sqlType, null);
    }

    public void setNull(int i, int sqlType, String typeName) throws SQLException {
        set(i, Param.NULL, sqlType, null);
    }

    public void setString(int i, String x) throws SQLException {
        set(i, Param.STRING, Types.VARCHAR, x);
    }

    public void setNString(int i, String x) throws SQLException {
        set(i, Param.STRING, Types.NVARCHAR, x);
    }

    public void setBoolean(int i, boolean x) throws SQLException {
        set(i, Param.BOOLEAN, Types.BOOLEAN, Boolean.toString(x));
    }

    public void setByte(int i, byte x) throws SQLException {
        set(i, Param.LONG, Types.TINYINT, Long.toString(x));
    }

    public void setShort(int i, short x) throws SQLException {
        set(i, Param.LONG, Types.SMALLINT, Long.toString(x));
    }

    public void setInt(int i, int x) throws SQLException {
        set(i, Param.LONG, Types.INTEGER, Long.toString(x));
    }

    public void setLong(int i, long x) throws SQLException {
        set(i, Param.LONG, Types.BIGINT, Long.toString(x));
    }

    public void setFloat(int i, float x) throws SQLException {
        set(i, Param.DOUBLE, Types.REAL, Double.toString(x));
    }

    public void setDouble(int i, double x) throws SQLException {
        set(i, Param.DOUBLE, Types.DOUBLE, Double.toString(x));
    }

    public void setBigDecimal(int i, BigDecimal x) throws SQLException {
        set(i, Param.DECIMAL, Types.DECIMAL, x == null ? null : x.toString());
    }

    public void setDate(int i, Date x) throws SQLException {
        set(i, Param.DATE, Types.DATE, x == null ? null : x.toString());
    }

    public void setDate(int i, Date x, Calendar cal) throws SQLException {
        setDate(i, x);
    }

    public void setTime(int i, Time x) throws SQLException {
        set(i, Param.TIME, Types.TIME, x == null ? null : x.toString());
    }

    public void setTime(int i, Time x, Calendar cal) throws SQLException {
        setTime(i, x);
    }

    public void setTimestamp(int i, Timestamp x) throws SQLException {
        set(i, Param.TIMESTAMP, Types.TIMESTAMP, x == null ? null : x.toString());
    }

    public void setTimestamp(int i, Timestamp x, Calendar cal) throws SQLException {
        setTimestamp(i, x);
    }

    public void setObject(int i, Object x) throws SQLException {
        if (x == null) {
            setNull(i, Types.NULL);
        } else if (x instanceof String) {
            setString(i, (String) x);
        } else if (x instanceof Boolean) {
            setBoolean(i, (Boolean) x);
        } else if (x instanceof BigDecimal) {
            setBigDecimal(i, (BigDecimal) x);
        } else if (x instanceof Double || x instanceof Float) {
            setDouble(i, ((Number) x).doubleValue());
        } else if (x instanceof Number) {
            setLong(i, ((Number) x).longValue());
        } else if (x instanceof Timestamp) {
            setTimestamp(i, (Timestamp) x);
        } else if (x instanceof Date) {
            setDate(i, (Date) x);
        } else if (x instanceof Time) {
            setTime(i, (Time) x);
        } else if (x instanceof java.util.Date) {
            setTimestamp(i, new Timestamp(((java.util.Date) x).getTime()));
        } else if (x instanceof LocalDateTime) {
            setTimestamp(i, Timestamp.valueOf((LocalDateTime) x));
        } else if (x instanceof LocalDate) {
            setDate(i, Date.valueOf((LocalDate) x));
        } else if (x instanceof LocalTime) {
            setTime(i, Time.valueOf((LocalTime) x));
        } else if (x instanceof Character) {
            setString(i, x.toString());
        } else {
            throw new SQLFeatureNotSupportedException(
                    "TxRay cannot transmit parameters of type " + x.getClass().getName());
        }
    }

    public void setObject(int i, Object x, int targetSqlType) throws SQLException {
        if (x == null) {
            setNull(i, targetSqlType);
        } else {
            setObject(i, x);
        }
    }

    public void setObject(int i, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
        setObject(i, x, targetSqlType);
    }
}
