package org.eclipse.txray.jdbc;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Savepoint;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

import org.eclipse.txray.jdbc.backend.Backend;
import org.eclipse.txray.jdbc.backend.ExecuteRequest;
import org.eclipse.txray.jdbc.backend.ExecuteResult;
import org.eclipse.txray.jdbc.backend.ServerInfo;

/**
 * A JDBC connection of DBeaver on an exposed connection. Transaction control (commit, rollback, auto-commit, close of
 * the real connection) is deliberately never forwarded: the transaction belongs to the debugged
 * application and DBeaver only looks into it.
 */
public final class TxRayConnection extends JdbcHandler {

    private final Backend backend;
    private final String url;
    /** null: follow the most recently exposed connection. */
    private final String bindingId;
    private volatile ServerInfo info;
    private volatile boolean closed;
    private boolean readOnly;

    private TxRayConnection(Backend backend, String url, String bindingId) {
        this.backend = backend;
        this.url = url;
        this.bindingId = bindingId;
    }

    static Connection open(Backend backend, String url, String bindingId) throws SQLException {
        TxRayConnection c = new TxRayConnection(backend, url, bindingId);
        c.info = backend.describe(bindingId);
        return c.proxy(Connection.class);
    }

    ExecuteResult execute(ExecuteRequest request) throws SQLException {
        ensureOpen();
        return backend.execute(bindingId, request);
    }

    ServerInfo refreshInfo() throws SQLException {
        ensureOpen();
        info = backend.describe(bindingId);
        return info;
    }

    ServerInfo info() {
        return info;
    }

    String url() {
        return url;
    }

    private void ensureOpen() throws SQLException {
        if (closed) {
            throw new SQLException("TxRay connection is closed", "08003");
        }
    }

    // ---- java.sql.Connection -------------------------------------------------------------

    public Statement createStatement() throws SQLException {
        ensureOpen();
        return new StatementHandler(this, null).proxy(Statement.class);
    }

    public Statement createStatement(int type, int concurrency) throws SQLException {
        return createStatement();
    }

    public Statement createStatement(int type, int concurrency, int holdability) throws SQLException {
        return createStatement();
    }

    public PreparedStatement prepareStatement(String sql) throws SQLException {
        ensureOpen();
        return new StatementHandler(this, sql).proxy(PreparedStatement.class);
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return prepareStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return prepareStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return prepareStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int type, int concurrency) throws SQLException {
        return prepareStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int type, int concurrency, int holdability)
            throws SQLException {
        return prepareStatement(sql);
    }

    public CallableStatement prepareCall(String sql) throws SQLException {
        ensureOpen();
        return new StatementHandler(this, sql).proxy(CallableStatement.class);
    }

    public CallableStatement prepareCall(String sql, int type, int concurrency) throws SQLException {
        return prepareCall(sql);
    }

    public CallableStatement prepareCall(String sql, int type, int concurrency, int holdability)
            throws SQLException {
        return prepareCall(sql);
    }

    public String nativeSQL(String sql) {
        return sql;
    }

    public DatabaseMetaData getMetaData() throws SQLException {
        ensureOpen();
        return new DatabaseMetaDataHandler(this).proxy(DatabaseMetaData.class);
    }

    /** Reported as true so that DBeaver never tries to drive the transaction itself. */
    public boolean getAutoCommit() {
        return true;
    }

    public void setAutoCommit(boolean autoCommit) {
        // the transaction belongs to the debugged application
    }

    public void commit() {
        // the transaction belongs to the debugged application
    }

    public void rollback() {
        // the transaction belongs to the debugged application
    }

    public void rollback(Savepoint savepoint) {
        // the transaction belongs to the debugged application
    }

    public void releaseSavepoint(Savepoint savepoint) {
        // the transaction belongs to the debugged application
    }

    public int getTransactionIsolation() {
        ServerInfo i = info;
        return i != null && i.transactionIsolation != 0 ? i.transactionIsolation
                : Connection.TRANSACTION_READ_COMMITTED;
    }

    public void setTransactionIsolation(int level) {
        // the transaction belongs to the debugged application
    }

    public boolean isReadOnly() {
        return readOnly;
    }

    public void setReadOnly(boolean readOnly) {
        this.readOnly = readOnly;
    }

    public String getCatalog() {
        return info.catalog;
    }

    public void setCatalog(String catalog) {
        // ignored: changing the catalog would alter the application's session
    }

    public String getSchema() {
        return info.schema;
    }

    public void setSchema(String schema) {
        // ignored: changing the schema would alter the application's session
    }

    public void close() {
        closed = true;
    }

    public void abort(Executor executor) {
        close();
    }

    public boolean isClosed() {
        return closed;
    }

    public boolean isValid(int timeout) {
        if (closed) {
            return false;
        }
        try {
            refreshInfo();
            return true;
        } catch (SQLException e) {
            return false;
        }
    }

    public SQLWarning getWarnings() {
        return null;
    }

    public void clearWarnings() {
        // no warnings
    }

    public int getHoldability() {
        return ResultSet.HOLD_CURSORS_OVER_COMMIT;
    }

    public Map<String, Class<?>> getTypeMap() {
        return new HashMap<>();
    }

    public Properties getClientInfo() {
        return new Properties();
    }

    public String getClientInfo(String name) {
        return null;
    }

    public void setClientInfo(String name, String value) throws SQLClientInfoException {
        // ignored
    }

    public void setClientInfo(Properties properties) throws SQLClientInfoException {
        // ignored
    }

    public int getNetworkTimeout() {
        return 0;
    }
}
